# Generated by Django 4.2 on 2023-05-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='photos')),
            ],
            options={
                'db_table': 'photo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('writedate', models.DateTimeField()),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('reward', models.IntegerField()),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
    ]
