# Generated by Django 4.2 on 2023-05-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(related_name='posts', to='postapp.photo'),
        ),
    ]
