# Generated by Django 4.2 on 2023-05-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_post_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='src',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
