# Generated by Django 4.2 on 2023-05-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_remove_photo_src_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
